import Head from "next/head";
import styles from "../styles/Home.module.css";
import { FaSearch } from "react-icons/fa";
import Nav from "../layouts/nav";
import { ThemeContext } from "../context/context";
import { useState } from "react";

export default function Home() {
  const [theme, setTheme] = useState("light");
  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    setTheme(newTheme);
    console.log(theme);
  };
  return (
    <ThemeContext.Provider value={{ toggleTheme }}>
      <div className={styles.container}>
        <Head>
          <title>Colorful Countries</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="author" content="Odiagbe Samson Osaro" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <div className={styles.inputAndFilterContainer}>
          <div className={styles.inputContainer}>
            <FaSearch />
            <input type="text" placeholder="Search for a country" />
          </div>
          <div className={styles.filter}>
            <select defaultValue={"Filter by Region"}>
              <option disabled>Filter by Region</option>
              <option>Africa</option>
              <option>America</option>
              <option>Asia</option>
              <option>Europe</option>
              <option>Oceania</option>
            </select>
          </div>
        </div>
        <div className={styles.countriesContainer}></div>
      </div>
    </ThemeContext.Provider>
  );
}
